version: "3.7"
services:
    # MySQL database for the app.
    mariadb:
        image: mariadb:latest
        container_name: maria
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=iotctl
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql
        tty: true
        networks:
            default:
                ipv4_address: 172.18.0.2

    # For convenient MySQL database management.
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=DB
        restart: always
        ports:
            - "8080:89"
        volumes:
            - /sessions
        links:
            - mariadb
        networks:
            default:
                ipv4_address: 172.18.0.4

    # Mosquitto MQTT Broker
    mqtt:
        image: eclipse-mosquitto
        hostname: mosquitto
        container_name: mosquitto
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
            - ./configs/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
        networks:
            default:
                ipv4_address: 172.18.0.3

    # Vue.js front-end
    frontend:
        build:
            context: web/ui
        ports:
            - "8081:8080"
        volumes:
            - ./web/ui:/app
        networks:
            default:
                ipv4_address: 172.18.0.5

networks:
    default:
        ipam:
            config:
                - subnet: 172.18.0.0/24
