broker: 
    type: "mqtt"
    clientid: "device-simulator"
    server: "tcp://172.18.0.3:1883"
    username: "devices"
    password: "test"
    protocolver: 3
devices:
    device1:
        name: TempReader1
        mac: "AA:BB:CC:DD:EE:01"
        sensors:
            - bmp180
        interface: "esp32"
        network: "global"
        battery: 2400.00
        statistics: "kitchen_1.txt"
        ipaddress4: "172.16.0.5"
