broker: 
    server: "tcp://172.18.0.3:1883"
    username: "device-sim"
    password: "test"
devices:
    device1:
        name: TempReader1
        mac: "AA:BB:CC:DD:EE:01"
        sensors:
            - bmp180
        interface: "esp32"
        network: "global"
        battery: 2400.00
        statistics: "kitchen_1.txt"
