export const FETCH_START = 'setLoading'
export const SET_NODE = 'setNode'
export const SET_NODES = 'setNodes'
export const PURGE_AUTH = 'logOut'
export const SET_ERROR = 'setError'
export const UPDATE_NODE_IN_LIST = 'updateNodeInList'
export const RESET_MODULE = 'resetModuleState'
export const RESET_STATE = 'resetState'
